### ISSUE TITLE
Allow to name the service in RSDL

### ISSUE THREAD

**Issue by chrisspre** [oasis-open/odata-rapid#121]

**Comment by chrisspre** [comment]
see https://github.com/oasis-open/odata-rapid/pull/125

**Comment by ralfhandl** [comment]
Why would we want to name the service? Do we plan to allow defining multiple services?

I had the impression we wanted to influence the _namespace_, not the _container_ name

**Comment by chrisspre** [comment]
> Why would we want to name the service? Do we plan to allow defining multiple services?
> 
> I had the impression we wanted to influence the _namespace_, not the _container_ name

Correct. this was only to accommodate what you where correcting in Mike's intro document `service jetsons { ... `

Are you proposing to a) have a default name for the container and b) use the RSDL service name as the namespace for the CSDL ?

**Comment by mikepizzo** [comment]
I don't think naming the service has value -- I like not having a name for the service since it's not used anywhere.

But, being able to optionally define the namespace might be useful.

Perhaps we can (optionally) annotate the service with a namespace?

@namespace: jetsons service {
    company: company
}

If not specified, maybe use "model"?

We could also allow defining additional namespaces by qualifying the type name (in its definition and use) which would implicitly define a separate namespace.

Here's what I was playing around with:

## Defining namespaces in RSDL

By default, all types are defined in a common namespace whose name is the name of the service (in the examples above, the namespace is "jetsons").

Sometimes it's convenient to group types into separate namespaces. Types can be defined in alternate namespaces by prefixing the type name, both in the declaration and in its use, with the namespace name, followed by a dot (.).

~~~rsdl
type naming.fullName
{
    firstName : string
    lastName : string
}
type employee
{
    @key id: integer
    name: naming.fullName
    title: string
}
~~~

**Comment by chrisspre** [comment]
I like it to be able to specify a namespace. 

It has a bit of a larger impact since I believe we a) need to be able to fully qualify (type-) names and b) import/reference other namespaces. 

I would suggest to not specify the namespace as an annotation and not so deep into the document.
I would suggest 
a) one namespace per document and 
b) an (optional ) declaration at the top of the document namespace "hello"  that specifies the namespace name. No needs for any braces since this is for the complete document. I believe that simplifies the syntax and makes it less obtrustive.

Happy to work on the namespace declaration and leave the reference/fqn design for later.

**Comment by ralfhandl** [comment]
@chrisspre I like your proposal, sketched some alternatives in #128, your (and my) preference is option 2.

**Comment by chrisspre** [comment]
PR for #118 is out and create a new task for namespace references

see: namespace imports and referencing types in imported models #131
