### ISSUE TITLE
formalizing the use of yarn vs npm for website and better automation of website build

### ISSUE THREAD

**Issue by chrisspre** [oasis-open/odata-rapid#283]
The integration of the interactive query editor (a react component) seems to create some issues.
@wtrocki  the main readme.md in /website suggests to use yarn but the docusaurus documentation always talks about using npm. The workflow in github for example also uses npm.  Can you please shed some light on what would be best to use?

**Comment by ralfhandl** [comment]
Just tested the website build with npm instead of yarn, and the main difference between the two is how they deal with our local package dependencies
~~~json
    "odata-uri": "file:../tools/odataUri",
    "odata-url-editor": "file:../tools/urlEditor",
~~~

* npm creates symbolic links to these packages in `website/node_modules`
* yarn copies the current snapshot of these packages into `website/node_modules`

Links would be great for local development with `docusaurus start`, but `docusaurus deploy` gets tripped up, "successfully" deploying the website without the JS code from the linked packages ☹️ 

So yarn is the only option here unless/until someone figures out how to `docusaurus deploy` with linked packages.
