### ISSUE TITLE
Filter capabilities

### ISSUE THREAD

**Issue by ralfhandl** [oasis-open/odata-rapid#30]
The $filter syntax of OData is often criticized as
- too hard to implement for servers
- too powerful
- too difficult for clients to correctly construct

Many services only allow a subset of the filter language, and have overall restrictions, plus restrictions per property.

We've identified typical patterns for filter capabilities per property and clustered them as [filter expression types](https://github.com/oasis-tcs/odata-vocabularies/blob/master/vocabularies/Org.OData.Capabilities.V1.md#FilterExpressionType).

Switching from a "restrictions" approach to a whitelist/capabilities approach we could express this via filter directives:
```graphql
type Task 
  @filterMultiValue(fields:["id"])
  @filterSearchExpression(fields:["name"])
  @filterSingleRange(fields:["createdAt"])
{
  id: ID! @RapidID 
  name: String! 
  createdAt: DateTimeOffset @readonly
}
```

This way only the fields list grows longer with more fields, and the fields themselves remain uncluttered.

And no filter directives means no filter - pure whitelist approach.

> OData do not explicitly list all CRUD access methods

We want to address this with https://github.com/oasis-open/odata-rapid/issues/10, which nicely combines with the filter directives:

```graphql
type Task 
  @readList
  @readSingle
  @update
  @filterMultiValue(fields:["id"])
  @filterSearchExpression(fields:["name"])
  @filterSingleRange(fields:["createdAt"])
{
  id: ID! @RapidID 
  name: String! 
  createdAt: DateTimeOffset @readonly
}
```

And yet another variation: make the filter capabilities optional arguments of `@readList`:
```graphql
type Task 
  @readList(
    filterMultiValue: ["id"],
    filterSearchExpression: ["name"],
    filterSingleRange: ["createdAt"]
  )
  @readSingle
  @update
{
  id: ID! @RapidID 
  name: String! 
  createdAt: DateTimeOffset @readonly
}
```

**Comment by chrisspre** [comment]
I was thinking about a slightly different direction for two reasons. a) these amount of annotations makes the RSDL hard to read and the syntax of annotations is quite constrained b) I believe that all capabilities should be pivoted on the allowed urls so that reasoning about it is easier.

I am going to propose a DSL in a secondary file that lists URLs and the corresponding allowed http methods, filters and other capabilities. Something like:

```
/users {
  POST { }
  GET {
    orderBy: displayName, upn,
    count: true
    filter {
        id, upn, displayName:   eq, ne, startsWith
        hiredate:               lt, le
        *:           eq
  }
}

/user/{id} {
    DELETE, PATCH { }
}

/me {
  GET {}
}
```

**Comment by chrisspre** [comment]
I was thinking about a slightly different direction for two reasons. a) these amount of annotations makes the RSDL hard to read and the syntax of annotations is quite constrained b) I believe that all capabilities should be pivoted on the allowed urls so that reasoning about it is easier.

I am going to propose a DSL in a secondary file that lists URLs and the corresponding allowed http methods, filters and other capabilities. Something like:

```
/users {
  POST { }
  GET {
    orderBy: displayName, upn,
    count: true
    filter {
        id, upn, displayName:   eq, ne, startsWith
        hiredate:               lt, le
        *:           eq
  }
}

/user/{id} {
    DELETE, PATCH { }
}

/me {
  GET {}
}
```

**Comment by wtrocki** [comment]
```
/users {
  POST { }
  GET {
    orderBy: displayName, upn,
    count: true
    filter {
        id, upn, displayName:   eq, ne, startsWith
        hiredate:               lt, le
        *:           eq
  }
}

/user/{id} {
    DELETE, PATCH { }
}

/me {
  GET {}
}
```

I do not have much voice here but really like what you have proposed. 
Although what you think about aliasing those:


````
alias SearchOperators = eq, ne, startsWith

/users {
  POST { }
  GET {
    orderBy: displayName, upn,
    count: true
    filter {
        id: SearchOperators,
        upn: SearchOperators
        hiredate:[le,ne]
	
  }
}

About wildcards
```
	// This is scary as it is potentially opening things to new fields that were added.
        *:           eq
```

Offtopic one:
Where we will get the connection from `/users/` to entity?

**Comment by chrisspre** [comment]
> I do not have much voice here but really like what you have proposed.
> Although what you think about aliasing those:
> 
> ```
> alias SearchOperators = eq, ne, startsWith
> 
> /users {
>   POST { }
>   GET {
>     orderBy: displayName, upn,
>     count: true
>     filter {
>         id: SearchOperators,
>         upn: SearchOperators
>         hiredate:[le,ne]
> 	
>   }
> }
> ```


Yes absolutely, I like it.
For larger descriptions this otherwise becomes unwieldy since this could be very repetitive.
I will look into it. 



> 
> About wildcards
> 
> ```
> 	// This is scary as it is potentially opening things to new fields that were added.
>         *:           eq
> ```

good point. this was just laziness from my side. There is an implicit assumption that whatever is not mentioned is not possible. This is the exact opposite and as you point out dagenrous. 

> 
> Offtopic one:
> Where we will get the connection from `/users/` to entity?

The assumption is that this accompanies a RAPID RSDL file (or CSDL file) and we will have a tool that a) checks that these segments (e.g. /users ) actually are valid relative URLs and b) in the future help to author this through editor suggestions by inspecting the RSDL file .

**Comment by ralfhandl** [comment]
> whatever is not mentioned is not possible

That should be the guiding principle: explicit allow-list

**Comment by chrisspre** [comment]
was incorporated into #249
