### ISSUE TITLE
Specify relationships (navigation) for RSDL

### ISSUE THREAD

**Issue by wtrocki** [oasis-open/odata-rapid#68]
Current doc have TODO. 
Considering complex nature of this capability I would like to have open conversation first before we add anything

**Comment by ralfhandl** [comment]
The leading double underscore is reserved by GraphQL for introspection, we could only use `_id_`

**Comment by wtrocki** [comment]
This is working fine. I'm using those fields as well in generator but it will be strange enough to type it.

**Comment by ralfhandl** [comment]
We are not trying to mimic OData with pure GraphQL means, we are just borrowing GraphQL _schema syntax_ for RSDL.

So `@id` is an implicitly defined property of OData JSON payloads, we don’t have to model it explicitly in RSDL, and we don’t have to worry about GraphQL  _data payload_ restrictions - we aren’t using it.

**Comment by GEricson** [comment]
My original goal here is simply to find a way to express a GraphQL conformant payload that represents references rather than objects.  The OData way is to embed the reference in an object with the implicit property name of @id or @odata.id.  To mimic this in a GraphQL payload, my first thought was to define an implicit property for the id, similar to type.  So __id in GraphQL.  If we go there, I'd suggest working with GraphQL team to reserve __id for the same purpose.  Other schemas could be used, for example: _odata_id or _rapid_id.  The only requirement is that the strategy should be unlikely to trip against explicitly defined property names.

**Comment by ralfhandl** [comment]
That’s an interesting exercise, and unnecessary for RAPID as my understanding is that we will stick with OData payloads.

**Comment by GEricson** [comment]
@ralfhandl 
I am not clear on how this helps code production using GraphQL tooling,  That code still needs to support CSDL.

With only modeling in a GraphQL conformant SDL, I expect two things:
1) GraphQL and OData remain islands
2) RAPID modelers will want the option to negotiate for payloads in RSDL.

**Comment by wtrocki** [comment]
CLosing as this is not longer needed.
